# Generated by Django 3.0.5 on 2020-04-17 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=30)),
                ('house_number', models.IntegerField()),
                ('street', models.CharField(max_length=30)),
                ('street_two', models.CharField(max_length=30)),
                ('town', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('postcode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=40)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('expense_dated', models.DateField()),
                ('date_from', models.DateField(blank=True)),
                ('date_to', models.DateField(blank=True)),
                ('amount', models.FloatField()),
                ('image', models.ImageField(null=True, upload_to='bill_image')),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=30)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residences', to='house_share.Address')),
                ('tenants', models.ManyToManyField(blank=True, related_name='residences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_to_pay', models.FloatField()),
                ('paid_flag', models.BooleanField()),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='house_share.Expense')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='house_share.Residence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='residence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='house_share.Residence'),
        ),
        migrations.AddField(
            model_name='expense',
            name='users_liable',
            field=models.ManyToManyField(blank=True, related_name='expenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
