# Generated by Django 3.0.5 on 2020-04-17 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house_share', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_in', models.DateField()),
                ('moved_out', models.DateField()),
                ('status', models.CharField(max_length=30)),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='house_share.Residence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
