# Generated by Django 3.0.5 on 2020-04-17 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house_share', '0002_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='admin_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='residence', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
