# Generated by Django 3.0.5 on 2020-04-17 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house_share', '0003_residence_admin_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_from', models.DateField()),
                ('for_duration', models.CharField(max_length=25)),
                ('room_details', models.CharField(max_length=250)),
                ('image', models.ImageField(null=True, upload_to='room_image')),
                ('cost_per_week', models.FloatField()),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='house_share.Residence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
