# Generated by Django 3.0.5 on 2020-04-17 21:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house_share', '0005_auto_20200417_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='join_requests',
            field=models.ManyToManyField(blank=True, related_name='new_residence', to=settings.AUTH_USER_MODEL),
        ),
    ]
