# Generated by Django 3.0.5 on 2020-04-19 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house_share', '0006_residence_join_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='address',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='residences', to='house_share.Address'),
        ),
    ]
