# Generated by Django 3.0.5 on 2020-04-19 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house_share', '0007_auto_20200419_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residences', to='house_share.Address'),
        ),
        migrations.AlterField(
            model_name='residence',
            name='join_requests',
            field=models.ManyToManyField(null=True, related_name='new_residence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='residence',
            name='tenants',
            field=models.ManyToManyField(null=True, related_name='residences', to=settings.AUTH_USER_MODEL),
        ),
    ]
