# Generated by Django 3.0.5 on 2020-04-19 22:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house_share', '0009_auto_20200419_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='join_requests',
            field=models.ManyToManyField(related_name='new_residence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='residence',
            name='tenants',
            field=models.ManyToManyField(related_name='residences', to=settings.AUTH_USER_MODEL),
        ),
    ]
