# Generated by Django 3.0.5 on 2020-04-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_share', '0010_auto_20200419_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='short_name',
            field=models.CharField(max_length=30),
        ),
    ]
