# Generated by Django 3.0.5 on 2020-04-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_share', '0011_auto_20200420_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residence',
            name='short_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
