# Generated by Django 3.0.5 on 2020-04-21 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_share', '0012_auto_20200420_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='split',
            name='residence',
        ),
    ]
