# Generated by Django 3.0.5 on 2020-04-21 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('house_share', '0013_remove_split_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='residence',
            name='past_tenants',
            field=models.ManyToManyField(related_name='past_residences', to=settings.AUTH_USER_MODEL),
        ),
    ]
