# Generated by Django 3.0.5 on 2020-04-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_share', '0014_residence_past_tenants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_from',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date_to',
            field=models.DateField(null=True),
        ),
    ]
